name: Question
description: Ask a question about setup, configuration, or usage.
title: "Question: "
labels: ["question"]
body:
  - type: textarea
    id: question
    attributes:
      label: Question
      description: What would you like to know?
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Context
      description: Anything that helps answer the question (board, logs, config).
    validations:
      required: false
