#ifndef SMALL_MOTOR_CONFIG_H
#define SMALL_MOTOR_CONFIG_H

#undef SAMPLING_FREQUENCY_HZ
#define SAMPLING_FREQUENCY_HZ 100

#undef WINDOW_SIZE
#define WINDOW_SIZE 256

#undef BAND_1_MAX
#undef BAND_2_MIN
#undef BAND_2_MAX
#undef BAND_3_MIN

#define BAND_1_MAX 20
#define BAND_2_MIN 20
#define BAND_2_MAX 50
#define BAND_3_MIN 50
#define BAND_3_MAX 100

#undef THRESHOLD_MULTIPLIER_WARNING
#undef THRESHOLD_MULTIPLIER_CRITICAL

#define THRESHOLD_MULTIPLIER_WARNING 1.5
#define THRESHOLD_MULTIPLIER_CRITICAL 2.5

#define MOTOR_TYPE "Small Motor"
#define MOTOR_RATED_RPM 1800
#define MOTOR_RATED_HP 0.5
#define MOTOR_POLES 4

#define MOTOR_FUNDAMENTAL_HZ (MOTOR_RATED_RPM / 60.0f)

#define FREQ_1X_RPM MOTOR_FUNDAMENTAL_HZ
#define FREQ_2X_RPM (MOTOR_FUNDAMENTAL_HZ * 2)
#define FREQ_BLADE_PASS (MOTOR_FUNDAMENTAL_HZ * 6)

#endif
